version: '3.8'

services:
  app:
    build:
      target: development
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules

  nginx:
    volumes:
      - ./docker/nginx/development.conf:/etc/nginx/conf.d/default.conf

profiles:
  - development