services:
  app:
    build:
      target: development
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - WWWUSER=1000
      - WWWGROUP=1000
    volumes:
      - .:/var/www/html:cached
      # Remove vendor and node_modules volumes to avoid conflicts during initial setup

  nginx:
    volumes:
      - ./docker/nginx/development.conf:/etc/nginx/conf.d/default.conf

  # Override to disable restart policy for development
  mysql:
    restart: "no"
    
  redis:
    restart: "no"